library(data.table)
# IMPORTANT IF YOU RUN THIS FILE FIRST, par() MUST BE RESET TO ORIGINAL WHEN RUNNING PREVIOUS FILES
# 1- read first line to be the column names
header<-read.table("hpc.txt",sep = ";",nrows = 3,header = TRUE)
headnames<-names(header)
# 2 -Read starting 1/2/2007 please acknowledge date in European format dd/mm/yyyy, and only read 2 days
# which in minutes 60*24*2=2880
datos<-fread("hpc.txt",sep = ";",skip = "1/2/2007",na.strings = "?",nrows = 2880,col.names = headnames)
library(lubridate)
dat2<-as.data.frame(datos)
dat2$new<-paste(dat2$Date,dat2$Time)
dat2$new<-dmy_hms(dat2$new)
par(mfrow=c(2,2),pty="s")
par(mar=c(4,4,1,1))
plot(dat2$new, dat2$Global_active_power, type="n",xlab="",ylab = "Global Active Power (kilowats)")
lines(dat2$new, dat2$Global_active_power, type="l")
plot(dat2$new, dat2$Voltage, type="n",xlab="datetime",ylab = "Voltage")
lines(dat2$new,dat2$Voltage,type="l",lwd=2)
with(dat2,plot(new, Sub_metering_1, type="n",xlab="",ylab = "Energy sub metering"))
with(dat2,lines(new, Sub_metering_1,type="l",col="black"))
with(dat2,lines(new, Sub_metering_2,type="l",col="red"))
with(dat2,lines(new, Sub_metering_3,type="l",col="blue"))
legend("topright",lwd=2,col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),text.font = 1)
plot(dat2$new, dat2$Global_reactive_power, type="n",xlab="datetime",ylab = "Global_reactive_power")
lines(dat2$new,dat2$Global_reactive_power,type="l")
dev.copy(png,file="plot4.png")
dev.off()